# Generated by Django 3.1.4 on 2020-12-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Origin',
                'verbose_name_plural': 'Origins',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Purpose',
                'verbose_name_plural': 'Purposes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('rank', models.PositiveIntegerField(verbose_name='Rank')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to='navyapp.origin', verbose_name='Origin')),
                ('purposes', models.ManyToManyField(related_name='aircrafts', to='navyapp.Purpose', verbose_name='Purpose')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircrafts',
                'ordering': ['name'],
            },
        ),
    ]
